{
 "title": "Dashboard practica sre",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Veces de arranque",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(changes(process_start_time_seconds{job=\"sre-fastapi\"}[24h]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cantidad de requests",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(server_requests_total)", "legendFormat": "{{label_name}}" }
   ]
  },
  {
   "title": "Requests al ep hi",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(hi_requests_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Requests por segundo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(server_requests_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}